### ISSUE TITLE
Using this code with TF02-PRO sensor

### ISSUE THREAD

**Issue by SIbrahimBZU** [madewhatnow/TFmini-I2C-Python#6]
Hi,

I am trying to connect a TF02-PRO sensor with a raspberry 4 using I2C protocol,
is it possible to use your codes to do that?
I tried that but I faced some errors that I think it is not related to changing the sensor.
Any help will be appreciated.
 
Thanks,

**Comment by madewhatnow** [comment]
Hi there, I don't have access to the TF02-PRO sensor, so unfortunately can't comment.
